/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerProdutos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelProdutos;
import util.Formatador;

/**
 *
 * @author user
 */
public class ViewProduto extends javax.swing.JFrame {

    ArrayList<ModelProdutos> listaModelProduto = new ArrayList<>();
    ControllerProdutos controllerProdutos = new ControllerProdutos();
    ModelProdutos modelProdutos = new ModelProdutos();
    String salvarAlterar;
    Formatador formatador = new Formatador();

    /**
     * Creates new form ViewProduto
     */
    public ViewProduto() {
        initComponents();
        carregarProdutos();
        setLocationRelativeTo(null);
        habilitarCampos(false);
        
    }

    private void habilitarCampos(boolean condicao) {
        txtNome.setEnabled(condicao);
        txtEstoque.setEnabled(condicao);
        txtValor.setEnabled(condicao);
    }

    private void limparCampos() {
        txtNome.setText("");
        txtEstoque.setText("");
        txtValor.setText("");
    }

    private void salvarProduto() {
        modelProdutos.setProdNome(this.txtNome.getText());
        modelProdutos.setProdEstoque(Integer.parseInt(this.txtEstoque.getText()));
        modelProdutos.setProdValor(formatador.converterVirgulaParaPonto(this.txtValor.getText()));

        if (controllerProdutos.salvarProdutoController(modelProdutos) > 0) {
            JOptionPane.showMessageDialog(this, "Produto Cadastrado com Sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            this.carregarProdutos();
            this.limparCampos();
            this.habilitarCampos(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao Cadastrar o Produto!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void alterarProduto() {
        modelProdutos.setProdNome(this.txtNome.getText());
        modelProdutos.setProdEstoque(Integer.parseInt(this.txtEstoque.getText()));
        modelProdutos.setProdValor(formatador.converterVirgulaParaPonto(this.txtValor.getText()));

        if (controllerProdutos.alterarProdutoController(modelProdutos)) {
            JOptionPane.showMessageDialog(this, "Produto Alterado com Sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            this.carregarProdutos();
            this.limparCampos();
            this.habilitarCampos(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao Alterar o Produto!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPesq = new javax.swing.JTextField();
        btnPesq = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProd = new javax.swing.JTable();
        btmCancel = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnAlt = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtEstoque = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRODUTOS");

        jPanel1.setToolTipText("Produtos");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 43, -1, -1));

        txtCod.setEditable(false);
        txtCod.setText(" ");
        txtCod.setEnabled(false);
        jPanel1.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 72, 78, -1));

        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 43, -1, -1));

        txtNome.setToolTipText("*DIGITE O TEXTO EM CAIXA ALTA");
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 72, 432, -1));

        jLabel3.setText("Estoque:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 127, -1, -1));

        jLabel4.setText("Valor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 127, -1, -1));

        jLabel5.setText("Pesquisar:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 210, -1, -1));
        jPanel1.add(txtPesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 207, 416, -1));

        btnPesq.setText("Pesquisar");
        btnPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 206, -1, -1));

        tblProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cód.", "Nome", "Quant.", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProd);
        if (tblProd.getColumnModel().getColumnCount() > 0) {
            tblProd.getColumnModel().getColumn(0).setMinWidth(75);
            tblProd.getColumnModel().getColumn(0).setPreferredWidth(75);
            tblProd.getColumnModel().getColumn(0).setMaxWidth(75);
            tblProd.getColumnModel().getColumn(2).setMinWidth(100);
            tblProd.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblProd.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 253, 643, 132));

        btmCancel.setText("Cancelar");
        btmCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btmCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 423, -1, -1));

        btnNew.setText("Novo");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel1.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 423, 84, -1));

        btnAlt.setText("Alterar");
        btnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 423, -1, -1));

        btnDel.setText("Excluir");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel1.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 423, -1, -1));

        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 423, 88, 37));

        txtEstoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtEstoque.setText("0");
        txtEstoque.setToolTipText("");
        jPanel1.add(txtEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, -1));

        jLabel6.setText("R$");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 150, 20, 30));

        txtValor.setText("0.00");
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        /*
         Metodo para Botão Salvar Produtos
         */
        if (this.salvarAlterar.equals("salvar")) {
            this.salvarProduto();
        } else {
            this.alterarProduto();
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        /*
         Metodo para Botão Deletar Produtos
         */
        int linha = tblProd.getSelectedRow();
        int codProd = (int) tblProd.getValueAt(linha, 0);
        if (controllerProdutos.excluirProdutosController(codProd)) {
            JOptionPane.showMessageDialog(this, "Produto Excluído com Sucesso!", " WA-WA-WIIUAH", JOptionPane.WARNING_MESSAGE);
            this.carregarProdutos();
            this.limparCampos();
            this.habilitarCampos(false);
        } else {
            JOptionPane.showMessageDialog(this, " Erro ao Excluir Produto!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        /*
         Metodo para Botão Novo
         */
        habilitarCampos(true);
        salvarAlterar = "salvar";
    }//GEN-LAST:event_btnNewActionPerformed

    private void btmCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCancelActionPerformed
        /*
         Metodo para Botão cancelar
         */
        this.habilitarCampos(false);
        this.limparCampos();
    }//GEN-LAST:event_btmCancelActionPerformed

    private void btnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltActionPerformed
        /*
         Metodo para Botão Alterar dados
         */
        salvarAlterar = "alterar";
        habilitarCampos(true);
        int linha = this.tblProd.getSelectedRow();

        try {
            int codProd = (int) this.tblProd.getValueAt(linha, 0);
            modelProdutos = controllerProdutos.retornarProdutoController(codProd);
            this.txtCod.setText(String.valueOf(modelProdutos.getProdId()));
            this.txtNome.setText(modelProdutos.getProdNome());
            this.txtEstoque.setText(String.valueOf(modelProdutos.getProdEstoque()));
            this.txtValor.setText(String.valueOf(modelProdutos.getProdValor()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Codigo Invalido ou Nenhum Registro Selecionado", "AVISO", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnAltActionPerformed

    private void btnPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqActionPerformed
        /*
         * Metodo para Botão Pesquisar Produtos
         * Refatorar com sistema de alto preenchimento como no ProjNilu
         */
        DefaultTableModel modelo = (DefaultTableModel) this.tblProd.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.tblProd.setRowSorter(classificador);
        String texto = this.txtPesq.getText();
        classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
    }//GEN-LAST:event_btnPesqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProduto().setVisible(true);
            }
        });
    }

    private void carregarProdutos() {
        listaModelProduto = controllerProdutos.retornarListaProdutoController();
        DefaultTableModel modelo = (DefaultTableModel) tblProd.getModel();
        modelo.setNumRows(0);
        int cont = listaModelProduto.size();

        for (int i = 0; i < cont; i++) {

            modelo.addRow(new Object[]{
                listaModelProduto.get(i).getProdId(),
                listaModelProduto.get(i).getProdNome(),
                listaModelProduto.get(i).getProdEstoque(),
                listaModelProduto.get(i).getProdValor()
            });

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmCancel;
    private javax.swing.JButton btnAlt;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnPesq;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProd;
    private javax.swing.JTextField txtCod;
    private javax.swing.JFormattedTextField txtEstoque;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesq;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
